FP21-69-swagger-documentation tools
HackYourFuture-CPH/kp-toolbox-fp-class21 pull request #21
Opened 2022-07-12 21:14 UTC by veronicaburduzhan

# Description

Please provide a short summary explaining what this PR is about.

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2022-07-12 22:29 UTC, alina-kho approved these changes

2022-07-13 10:19 UTC, somayehdvr approved these changes
You've left one unchanged :)

2022-07-13 10:19 UTC, somayehdvr commented on packages/server/api/routes/tools.router.js
> + *      Will return all exampleResource.
```suggestion
 *      Will return all tools.
```

2022-07-13 11:51 UTC, shpomp requested changes

2022-07-13 11:51 UTC, shpomp commented on packages/server/api/routes/tools.router.js
> + *       name: ID
This will not be read the same as "id" and it will not make it work. 
I assume swagger was not tested then, before making the PR - that should always be done.

2022-07-13 11:54 UTC, veronicaburduzhan commented on packages/server/api/routes/tools.router.js
> + *       name: ID
So this swagger should be removed for now?

2022-07-13 12:25 UTC, shpomp commented on packages/server/api/routes/tools.router.js
> + *       name: ID
This should be fixed so that the tools/{id} endpoint in swagger works :)

2022-07-13 12:49 UTC, shpomp approved these changes
🤩

2022-07-13 13:36 UTC, merged