Feature/fp21 11 landing page background container
HackYourFuture-CPH/kp-toolbox-fp-class21 pull request #3
Opened 2022-06-27 08:40 UTC by rebeccahockley

Added background container with CSS styles according to Figma stylings. Have added one media query for responsiveness and will add to this as we progress through the project. 

Run the code and look in the browser to see the different views at various windows widths.

2022-06-27 10:33 UTC, te-online reviewed
Good work 👍 I left two comments below. Didn't do any functional testing, maybe you could ask someone from another team to do that? 🙂

2022-06-27 14:49 UTC, mag-da-lenka commented on packages/client/src/components/Main/Main.css
> +    url('../../../public/assets/images/body-background-image-concrete.png');
Ehh, those heavy concrete structures. Good news though :D 
![image](https://user-images.githubusercontent.com/51802866/175969543-9c5cc120-93a1-454c-950d-e8e394d29f7c.png)

2022-06-27 14:50 UTC, mag-da-lenka commented on packages/client/src/components/Main/Main.css
> +    url('../../../public/assets/images/body-background-image-concrete.png');
![image](https://user-images.githubusercontent.com/51802866/175969808-0e86fd2d-faba-45db-a0f6-6c10d215e474.png)

2022-06-27 17:04 UTC, te-online approved these changes

2022-06-27 19:45 UTC, ricardoaguiar approved these changes

2022-07-01 08:34 UTC, oleksandra-lavryk commented on packages/client/src/containers/LandingPage/LandingPage.Style.css
> +  color: #ffffff;
@rebeccahockley  Hi. Everything looks good. But we need to change color format to RGB.

2022-07-01 08:35 UTC, oleksandra-lavryk requested changes
Take a look at the comment below.

2022-07-01 08:39 UTC, oleksandra-lavryk approved these changes
👍

2022-07-01 08:39 UTC, merged