FP21-82-add-about-us-page about toolbox page
HackYourFuture-CPH/kp-toolbox-fp-class21 pull request #45
Opened 2022-08-09 19:46 UTC by MJanOthman

# Description

About toolbox page
This is not the final code, I used fake background picture and text.

# How to test?

run server and client 

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2022-08-09 19:49 UTC, hassou2n approved these changes

2022-08-10 10:16 UTC, Divyajg requested changes
KaosPilot-image is not responsive, fix that one.
The content is overflowing in several situations.
![image](https://user-images.githubusercontent.com/81112710/183875156-a394f732-3f36-40e9-a61f-7297edc73279.png)
![image](https://user-images.githubusercontent.com/81112710/183873991-2c535296-52fa-4dc9-9529-16565bf38411.png)

2022-08-10 10:16 UTC, Divyajg commented on packages/client/src/components/AboutToolbox/AboutToolbox.style.css
> +.container {
Try naming this class more specific
For ex: about-toolbox-container

2022-08-10 10:16 UTC, Divyajg commented on packages/client/src/components/AboutToolbox/AboutToolbox.style.css
> +  align-items: center;
Does these styles `display: flex;
  justify-content: center;
  align-items: center;` make any difference?

2022-08-10 10:16 UTC, Divyajg commented on packages/client/src/components/AboutToolbox/AboutToolbox.style.css
> +@media screen and (max-width: 650px) {
The page beyond this width is acting weird. A couple of items are flowing out of the scope.

2022-08-10 10:16 UTC, Divyajg commented on packages/client/src/components/AboutToolbox/AboutToolbox.style.css
> +  width: 80%;
With width, try `margin:auto;`

2022-08-10 10:16 UTC, Divyajg commented on packages/client/src/components/AboutToolbox/AboutToolbox.style.css
> +@media screen and (max-width: 650px) {
Style the media screen with `min-width: 651px` for screens larger than 650px.

2022-08-10 20:24 UTC, MJanOthman commented on packages/client/src/components/AboutToolbox/AboutToolbox.style.css
> +  width: 80%;
Some elements need different  values of margin.

2022-08-14 11:16 UTC, Kristoffer88 approved these changes

2022-08-14 19:52 UTC, Divyajg approved these changes
Everything looks good except the toolbox-text is over-flowing out of the background image and I left you a comment about media queries.

2022-08-14 19:52 UTC, Divyajg commented on packages/client/src/components/AboutToolbox/AboutToolbox.style.css
> +@media screen and (max-width: 650px) {
You can use`(min-width: 651px)` and `(max-width: 650px)`, or `(max-width: 750px)` and `(min-width: 751px)` or `(max-width: 1230px)` and `(min-width: 1231px)` not all at once.
FYI: [Media queries width](https://www.freecodecamp.org/news/media-queries-width-ranges/#:~:text=Taking%20a%20look%20at%20the,extra%2Dsmall%20and%20small%20widths.)

2022-08-14 20:19 UTC, merged