Fp21 138 favourite icons logic
HackYourFuture-CPH/kp-toolbox-fp-class21 pull request #62
Opened 2022-08-21 12:35 UTC by sergii-borodin

# Description

Enable Favourites icons to start user authentication by clicking on them.
Fixes # (issue)

# How to test?

Start backend and frontend
# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2022-08-21 12:49 UTC, oleksandra-lavryk approved these changes

2022-08-21 13:41 UTC, te-online requested changes

2022-08-21 13:41 UTC, te-online commented on packages/client/src/components/Navigation/Navbar.component.js
> +              className={`navbar-link `}
You can simplify this to `className="navbar-link"` without the template literals and brackets. They seem to be a leftover from before.

2022-08-21 13:41 UTC, te-online commented on packages/client/src/components/ToolItem/ToolItem.component.js
> +    if (user) {
You don't need to check for user here, as it is the same as checking for userId. We can move the `else` branch to the `if(userId)` instead

2022-08-21 14:02 UTC, te-online requested changes

2022-08-21 14:02 UTC, te-online commented on packages/client/src/components/ToolItem/ToolItem.component.js
> +            user_id: userId,
This looks like a serious problem: What if you send `user_id: 'someone elses userid'`? Can you then change another user's favorites? The API should set the user_id automatically

2022-08-23 19:41 UTC, te-online approved these changes

2022-08-23 20:30 UTC, merged